language: python
sudo: false

before_install:
  - pip install hererocks
  - hererocks lua -r^ -l5.3.3
  - export PATH=$PATH:$PWD/lua/bin

install:
  - luarocks install busted
  - luarocks install moonscript

script:
  - make test
  - make testdist

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
